version = 1

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "vue",
    "angularjs",
    "angular"
  ]

[[transformers]]
name = "dotnet-format"
enabled = true

[[transformers]]
name = "prettier"
enabled = true